module.exports = {
  parser: "vue-eslint-parser",
  plugins: ["vue"],
  extends: ["plugin:vue/recommended"],
  parserOptions: {
    parser: "babel-eslint",
  },
  rules: {
    // Disable conflicts with prettier
    "vue/html-self-closing": "off",
    "vue/max-len": "off",
    "vue/array-bracket-spacing": "off",
    "vue/arrow-spacing": "off",
    "vue/block-spacing": "off",
    "vue/brace-style": "off",
    "vue/comma-dangle": "off",
    "vue/dot-location": "off",
    "vue/html-closing-bracket-newline": "off",
    "vue/html-closing-bracket-spacing": "off",
    "vue/html-end-tags": "off",
    "vue/html-indent": "off",
    "vue/html-quotes": "off",
    "vue/key-spacing": "off",
    "vue/keyword-spacing": "off",
    "vue/max-attributes-per-line": "off",
    "vue/multiline-html-element-content-newline": "off",
    "vue/mustache-interpolation-spacing": "off",
    "vue/no-multi-spaces": "off",
    "vue/no-spaces-around-equal-signs-in-attribute": "off",
    "vue/object-curly-spacing": "off",
    "vue/script-indent": "off",
    "vue/singleline-html-element-content-newline": "off",
    "vue/space-infix-ops": "off",
    "vue/space-unary-ops": "off",

    "vue/component-tags-order": [
      "error",
      { order: ["template", "script", "style"] },
    ],
    "vue/camelcase": "error",
    "vue/component-name-in-template-casing": "error",
    "vue/no-boolean-default": "error",
    "vue/no-reserved-component-names": "error",
    // "vue/no-static-inline-styles": "error",
    // "vue/no-template-target-blank": "error",
    "vue/padding-line-between-blocks": "error",
    "vue/require-direct-export": "error",
    "vue/v-on-function-call": ["error", "never"],
  },
};
